---
- name: Install requirements
  package:
    name: apt-transport-https
    state: present
  tags:
    - package
  become: true

- name: Add sublime text apt key
  apt_key:
    state: present
    url: https://download.sublimetext.com/sublimehq-pub.gpg
  tags:
    - apt_key
  become: true

- name: Add sublime text apt repository
  apt_repository:
    filename: sublime-text.list
    repo: "deb https://download.sublimetext.com/ apt/stable/"
    state: present
    update_cache: true
  tags:
    - apt_repository
  become: true
