---
- name: Add RPM key
  rpm_key:
    key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    state: present
  tags:
    - rpm_key
  become: true

- name: Add sublime repo
  yum_repository:
    enabled: true
    file: sublime-text
    baseurl: https://download.sublimetext.com/rpm/stable/x86_64
    gpgkey: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    gpgcheck: true
    description: Sublime Text - x86_64 - Stable
    name: sublime-text
    state: present
  tags:
    - yum_repository
  become: true
